### ISSUE TITLE
Clarification - just for sections?

### ISSUE THREAD

**Issue by jamiepittock** [joshangell/craft-unique-value#4]
Hi Josh, does this fieldtype only work for entries or could I use it as a user field? I scanned over the code and saw a couple of references to `$entryId`.

**Comment by joshangell** [comment]
Hi Jamie,

I'm afraid it does only work with Entries - equally I've not used it since I developed it so it may not completely work, I've no idea! It would be great if you do use it if you could tell me what version of Craft it works on :)

Thanks,

-Josh

**Comment by jamiepittock** [comment]
Thanks Josh. I need to gives users the ability to choose a unique slug to use as part of their public profile URL. The site uses email addresses as usernames so we can't use that field.

So it wouldn't be a good fit as-is. I might use it as a starting point for a new plugin though if the license permits?

**Comment by joshangell** [comment]
Of course! Have at it :)

-Josh

**Comment by jamiepittock** [comment]
Thanks Josh.
